// <auto-generated />
using System;
using MagicVilla_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230303174749_AddInitialRecords")]
    partial class AddInitialRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SquareMeter")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            Capacity = 5,
                            Cost = 200.0,
                            CreatedDate = new DateTime(2023, 3, 3, 11, 47, 49, 298, DateTimeKind.Local).AddTicks(369),
                            Detail = "Detalle de la Villa...",
                            ImageUrl = "",
                            Name = "Villa Real",
                            SquareMeter = 50,
                            UpdatedDate = new DateTime(2023, 3, 3, 11, 47, 49, 298, DateTimeKind.Local).AddTicks(439)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            Capacity = 4,
                            Cost = 150.0,
                            CreatedDate = new DateTime(2023, 3, 3, 11, 47, 49, 298, DateTimeKind.Local).AddTicks(446),
                            Detail = "Detalle de la Villa...",
                            ImageUrl = "",
                            Name = "Premium Vista a la Piscina",
                            SquareMeter = 40,
                            UpdatedDate = new DateTime(2023, 3, 3, 11, 47, 49, 298, DateTimeKind.Local).AddTicks(448)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
